### ISSUE TITLE
Call to a member function bundle() on null

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/layout_wildcard#17] opened 2021-04-20 17:13 UTC
Testing this out again on a site and after installation I can't create content. I get a fatal with the following error message:

> Error: Call to a member function bundle() on null in EntityBundleLayoutAccess->checkAccess() (line 77 of /app/core/modules/layout/plugins/access/entity_bundle_layout_access.inc).

Disabling this module gives me access to create content again.

**Comment by laryn** [comment] 2021-04-20 17:15
Sounds very similar to https://github.com/backdrop-contrib/layout_wildcard/issues/6

**Comment by laryn** [comment] 2021-04-20 17:44
I've gone through on a staging site and disabled all non-core modules (even if I had to delete fields, etc. to disable them) but I'm still getting this. I'll keep digging to see if I can turn anything up...

**Comment by bugfolder** [comment] 2021-04-20 18:04
Just out of curiosity: does the test site have "show preview for creation of new nodes" turned on? There's a long-standing bug in core 1.18.2, which is reproduced (currently) in LW. (Waiting for the core fix to be accepted—or not—before rolling it into LW.)

**Comment by bugfolder** [comment] 2021-04-20 18:27
The core issue I was referring to is addressed in PR https://github.com/backdrop-contrib/layout_wildcard/pull/16, which hasn't yet been incorporated into a release. Do you see the same behavior in LW 1.x-1.2.1 release and the current Github version?

**Comment by laryn** [comment] 2021-04-20 21:36
@bugfolder I dropped the replacement code in from that PR and cleared caches. Trying to create content on the staging site gives the same error, unfortunately.

**Comment by bugfolder** [comment] 2021-04-20 21:42
OK, that's pretty puzzling then. I've been trying to reproduce it on test sites and not getting it (and in theory, in the absence of any settings, the LW code just reproduces what happens in core).

If we can find a reproducible set of circumstances, I can go spelunking with the debugger. Meanwhile, is it possible to obtain a backtrace from the error? (There's a call to checkAccess() on line 141 in .module that looks suspicious, given the error.)

**Comment by laryn** [comment] 2021-04-22 06:48
@bugfolder I dug up something else in the logs. 

> Warning: call_user_func_array() expects parameter 2 to be array, string given in layout_wildcard_get_layout_by_path() (line 132 of /app/modules/layout_wildcard/layout_wildcard.module).

And here's a `debug_print_backtrace();` (is there a way to print this in a prettier format?):


`#0 layout_wildcard_get_layout_by_path(, Array ([path] => node/add/page,[load_functions] => ,[to_arg_functions] => ,[access_callback] => node_access,[access_arguments] => a:2:{i:0;s:6:"create";i:1;s:4:"page";},[page_callback] => node_add,[page_arguments] => Array ([0] => page),[fit] => 7,[number_parts] => 3,[tab_parent] => ,[tab_root] => node/add/page,[title] => Page,[title_callback] => check_plain,[title_arguments] => ,[type] => 6,[description] => A page, similar in form to a story, is a simple method for creating and displaying information that rarely changes, such as an "About us" section of a website. By default, a page entry does not allow visitor comments and is not featured on the site's initial home page.,[position] => ,[weight] => 0,[include_file] => core/modules/node/node.pages.inc,[delivery_callback] => ,[context] => 0,[theme_callback] => ,[theme_arguments] => Array (),[href] => node/add/page,[tab_root_href] => node/add/page,[tab_parent_href] => ,[options] => Array (),[access] => 1,[localized_options] => Array ([html] => 1),[original_map] => Array ([0] => node,[1] => add,[2] => page),[map] => Array ([0] => node,[1] => add,[2] => page))) called at [/app/modules/layout_wildcard/layout_wildcard.module:29] #1 layout_wildcard_route_handler(Array ([path] => node/add/page,[load_functions] => ,[to_arg_functions] => ,[access_callback] => node_access,[access_arguments] => a:2:{i:0;s:6:"create";i:1;s:4:"page";},[page_callback] => node_add,[page_arguments] => Array ([0] => page),[fit] => 7,[number_parts] => 3,[tab_parent] => ,[tab_root] => node/add/page,[title] => Page,[title_callback] => check_plain,[title_arguments] => ,[type] => 6,[description] => A page, similar in form to a story, is a simple method for creating and displaying information that rarely changes, such as an "About us" section of a website. By default, a page entry does not allow visitor comments and is not featured on the site's initial home page.,[position] => ,[weight] => 0,[include_file] => core/modules/node/node.pages.inc,[delivery_callback] => ,[context] => 0,[theme_callback] => ,[theme_arguments] => Array (),[href] => node/add/page,[tab_root_href] => node/add/page,[tab_parent_href] => ,[options] => Array (),[access] => 1,[localized_options] => Array ([html] => 1),[original_map] => Array ([0] => node,[1] => add,[2] => page),[map] => Array ([0] => node,[1] => add,[2] => page))) called at [/app/core/includes/menu.inc:531] #2 menu_execute_active_handler() called at [/app/index.php:21] 
`

**Comment by bugfolder** [comment] 2021-04-22 13:25
A few search-and-replaces turns it into
```
#0 layout_wildcard_get_layout_by_path(, 
  Array (
    [path] => node/add/page,
    [load_functions] => ,
    [to_arg_functions] => ,
    [access_callback] => node_access,
    [access_arguments] => a:2:{i:0;s:6:"create";i:1;s:4:"page";},
    [page_callback] => node_add,
    [page_arguments] => Array ([0] => page),
    [fit] => 7,
    [number_parts] => 3,
    [tab_parent] => ,
    [tab_root] => node/add/page,
    [title] => Page,
    [title_callback] => check_plain,
    [title_arguments] => ,
    [type] => 6,
    [description] => A page, similar in form to a story, is a simple method for creating and displaying information that rarely changes, such as an "About us" section of a website. By default, a page entry does not allow visitor comments and is not featured on the site's initial home page.,
    [position] => ,
    [weight] => 0,
    [include_file] => core/modules/node/node.pages.inc,
    [delivery_callback] => ,
    [context] => 0,
    [theme_callback] => ,
    [theme_arguments] => Array (),
    [href] => node/add/page,
    [tab_root_href] => node/add/page,
    [tab_parent_href] => ,
    [options] => Array (),
    [access] => 1,
    [localized_options] => Array ([html] => 1),
    [original_map] => Array ([0] => node,
    [1] => add,
    [2] => page),
    [map] => Array ([0] => node,
    [1] => add,
    [2] => page))) called at [/app/modules/layout_wildcard/layout_wildcard.module:29] 

#1 layout_wildcard_route_handler(Array ([path] => node/add/page,
    [load_functions] => ,
    [to_arg_functions] => ,
    [access_callback] => node_access,
    [access_arguments] => a:2:{i:0;s:6:"create";i:1;s:4:"page";},
    [page_callback] => node_add,
    [page_arguments] => Array ([0] => page),
    [fit] => 7,
    [number_parts] => 3,
    [tab_parent] => ,
    [tab_root] => node/add/page,
    [title] => Page,
    [title_callback] => check_plain,
    [title_arguments] => ,
    [type] => 6,
    [description] => A page, similar in form to a story, is a simple method for creating and displaying information that rarely changes, such as an "About us" section of a website. By default, a page entry does not allow visitor comments and is not featured on the site's initial home page.,
    [position] => ,
    [weight] => 0,
    [include_file] => core/modules/node/node.pages.inc,
    [delivery_callback] => ,
    [context] => 0,
    [theme_callback] => ,
    [theme_arguments] => Array (),
    [href] => node/add/page,
    [tab_root_href] => node/add/page,
    [tab_parent_href] => ,
    [options] => Array (),
    [access] => 1,
    [localized_options] => Array ([html] => 1),
    [original_map] => Array ([0] => node,
    [1] => add,
    [2] => page),
    [map] => Array ([0] => node,
    [1] => add,
    [2] => page))) called at [/app/core/includes/menu.inc:531] 

#2 menu_execute_active_handler() called at [/app/index.php:21]
```
An interesting thing is the log error. The code at line 132 is
```
 $context_data = call_user_func_array($context_info['load callback'], $router_item['original_map'][$context->position]);
```
Will examine further.

**Comment by bugfolder** [comment] 2021-04-22 13:39
Interesting...that line duplicates the code in the core routine `layout_get_layout_by_path()`...but the second argument will always be a string, not an array, so if that bit of code is ever reached, it should throw that warning, even with the module disabled.

But evidently LW is returning a layout in `$layouts = layout_wildcard_load_multiple_by_path('node/%', TRUE);` that sends us down that branch.

**Comment by laryn** [comment] 2021-04-22 15:28
Further troubleshooting info: if I wrap that structure as follows I avoid the fatal error:

```
    if (arg(1) != 'add') {
      if ($preview_node) {
        $layouts = layout_wildcard_load_multiple_by_path('node/%', TRUE);
      }
      else {
        $layouts = layout_wildcard_load_multiple_by_path($router_item['path'], TRUE);
      }
    }

```

**Comment by bugfolder** [comment] 2021-04-22 15:32
Can you dump the value of $layouts (after that bit of code) to a log file before the crash happens?

**Comment by laryn** [comment] 2021-04-22 15:41
It's empty if the `arg(1)` test wrapper is there, otherwise it contains 6 `node/%` context layout objects.

(Originally there were 5 `node/%` layouts, all with visibility conditions. I created a sixth generic one with no visibility conditions as a test but it didn't solve it either.)

**Comment by bugfolder** [comment] 2021-04-22 15:45
Aha. That strongly suggests that the ancestor matching is running amok. (That's something that has bugged me since I first started getting into this module.) Any way you can provide the full structure?

**Comment by bugfolder** [comment] 2021-04-22 15:48
In your `node/%` layouts, what is the context type of the `%` placeholders? nids?

**Comment by laryn** [comment] 2021-04-22 15:55
![Screen Shot 2021-04-22 at 10 54 26 AM](https://user-images.githubusercontent.com/871421/115745604-36b23e80-a359-11eb-90c3-9114ae6f8b53.jpg)

**Comment by bugfolder** [comment] 2021-04-22 16:02
OK yep, it's a node context. So pretty sure of what's going on, but I'll try to set it up locally and duplicate.

At the risk of being totally wrong, here's my tentative theory. LW has had this feature for a while that I've taken to calling "ancestor matching": it will say a layout is applicable to a path if the layout's path matches _any ancestor_ of the path. So since node/% is an ancestor of node/add/page, LW includes those layouts. But all of those layouts think that the thing in the second argument of the path is a nid, and 'add' isn't a nid. Things go downhill from there.

On my longer-term to-do list for LW is to make ancestor matching optional in the settings (currently, it's on all the time).

But for now, let me go try to set this up and see if I can reproduce the crash. (This may take a little while.)

**Comment by bugfolder** [comment] 2021-04-22 16:27
OK, I can reproduce it. On a vanilla Backdrop installation:
1. Enable Layout Wildcard
2. Create a Layout with path `node/%` (which is set by core to be of type Node).
3. Add a visibility condition (e.g., "node is type Page")
4. Go to `node/add/page`. Boom!

The visibility condition is essential for the crash. No visibility condition, it works fine. (This is almost certainly because of the mismatch between 'add' as the value of the placeholder and the context's expectation that it should be a nid, needed to check the type of the node; there's no node with nid='add'.)

So ancestor matching is the culprit. It will take a little more exploration to figure out what the best fix is.

**Comment by bugfolder** [comment] 2021-04-22 17:48
OK, I have **a** fix. Not sure yet if it's the **best** fix. I've attached a patch that fixes the problem on my test setup. Can you see if it fixes it on yours?

The root cause of the problem is indeed the fact that the ancestor matching feature of LW leads to the visibility condition attempting to interpret 'add' as a nid. What the patch does is say "well, if the value passed to the context doesn't lead to valid context data, we shouldn't have been trying to use this layout, so we'll move on to the next one in the list."

[lw_issue17.patch.txt](https://github.com/backdrop-contrib/layout_wildcard/files/6360281/lw_issue17.patch.txt)

The reason I'm not sure this is the best solution is that I don't know if there's ever a scenario in which $context->data for a positioned value could legitimately have the value FALSE.

And more broadly, because ancestor matching matches [SO MANY things](https://docs.backdropcms.org/api/backdrop/core%21includes%21menu.inc/function/menu_get_ancestors/1), it's a rather blunt tool for layout path matching with lots of potential for unexpected side effects (like this one). Seems like LW needs some more refined settings (e.g., an option "only match ancestors that have the same number of positions as the path"). So that needs some careful thought of how best to provide more refined controls while staying backwards-compatible with however many sites have already adopted it.

Anyhow, please try out the patch and let me know if it works for you.

**Comment by laryn** [comment] 2021-04-24 12:59
@bugfolder FWIW I manually patched the dev site I've been hacking on, and this does seem to solve the problem. Nice sleuthing!

**Comment by bugfolder** [comment] 2021-04-24 13:23
Great! Now to figure out what the best permanent fix is. I'll leave this issue open until there's something in place.

**Closed as completed** 2021-04-25 23:11 UTC

**Comment by bugfolder** [comment] 2021-04-25 23:12
After further thought, this does seem like the best fix for now. Committed via https://github.com/backdrop-contrib/layout_wildcard/pull/18. New bugfix release to follow shortly.
